<%@ Page Language="C#" MasterPageFile="~/MasterPage.Master" AutoEventWireup="true" CodeBehind="GridViewForm.aspx.cs" Inherits="ProjectForm.GridViewForm" %>
 <asp:Content ID="GridviewHead" runat="server" ContentPlaceHolderID="head"></asp:Content>
           
 <asp:Content ID="GridviewBody" runat="server" ContentPlaceHolderID="ContentPlaceHolder1">
       <div>
 <table>
     <tr>
         <td>
             <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True"   
                    AutoGenerateEditButton="True" DataKeyNames="id" onrowcancelingedit="GridView1_RowCancelingEdit"   
                    onrowdeleting="GridView1_RowDeleting" onrowediting="GridView1_RowEditing"   
                    onrowupdating="GridView1_RowUpdating"  ><Columns>  
                  <asp:TemplateField HeaderText="firstName">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="txtfirstName" runat="server" Text='<%# Bind("Firstname") %>'></asp:TextBox>  
                            </EditItemTemplate>  
                            <ItemTemplate>  
                                <asp:Label ID="lblfirstName" runat="server" Text='<%# Bind("Firstname") %>'></asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField>  


                  <asp:TemplateField HeaderText="lastName">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="txtlastName" runat="server" Text='<%# Bind("Lastname") %>'></asp:TextBox>  
                            </EditItemTemplate>  
                            <ItemTemplate>  
                                <asp:Label ID="lbllastName" runat="server" Text='<%# Bind("Lastname") %>'></asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField>  

                                <asp:TemplateField HeaderText="id">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="txtid" runat="server" Text='<%# Bind("Id") %>'></asp:TextBox>  
                            </EditItemTemplate>  
                            <ItemTemplate>  
                                <asp:Label ID="txtid" runat="server" Text='<%# Bind("id") %>'></asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField>  

                                <asp:TemplateField HeaderText="emailId">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="txtemailId" runat="server" Text='<%# Bind("EmailId") %>'></asp:TextBox>  
                            </EditItemTemplate>  
                            <ItemTemplate>  
                                <asp:Label ID="Label1" runat="server" Text='<%# Bind("EmailId") %>'></asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField>  

                           <asp:TemplateField HeaderText="gender">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="txtgender" runat="server" Text='<%# Bind("Gender") %>'></asp:TextBox>  
                            </EditItemTemplate>  
                            <ItemTemplate>  
                                <asp:Label ID="txtgender" runat="server" Text='<%# Bind("Gender") %>'></asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField> 

                         <asp:TemplateField HeaderText="mobileNumber">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="txtmobileNumber" runat="server" Text='<%# Bind("MobileNumber") %>'></asp:TextBox>  
                            </EditItemTemplate>  
                            <ItemTemplate>  
                                <asp:Label ID="txtmobileNumber" runat="server" Text='<%# Bind("MobileNumber") %>'></asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField> 


                          <asp:TemplateField HeaderText="dob">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="txtdob" runat="server" Text='<%# Bind("Dob") %>'></asp:TextBox>  
                            </EditItemTemplate>  
                            <ItemTemplate>  
                                <asp:Label ID="txtdob" runat="server" Text='<%# Bind("Dob") %>'></asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField> 

                         <asp:TemplateField HeaderText="doj">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="txtdoj" runat="server" Text='<%# Bind("Doj") %>'></asp:TextBox>  
                            </EditItemTemplate>  
                            <ItemTemplate>  
                                <asp:Label ID="txtdoj" runat="server" Text='<%# Bind("Doj") %>'></asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField> 

                         <asp:TemplateField HeaderText="userName">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="txtuserName" runat="server" Text='<%# Bind("UserName") %>'></asp:TextBox>  
                            </EditItemTemplate>  
                            <ItemTemplate>  
                                <asp:Label ID="lbluserName" runat="server" Text='<%# Bind("UserName") %>'></asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField> 


                          <asp:TemplateField HeaderText="password">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="txtpassword" runat="server" Text='<%# Bind("Password") %>'></asp:TextBox>  
                            </EditItemTemplate>  
                            <ItemTemplate>  
                                <asp:Label ID="lblpassword" runat="server" Text='<%# Bind("Password") %>'></asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField> 

                         <asp:TemplateField HeaderText="designation">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="txtdesignation" runat="server" Text='<%# Bind("Designation") %>'></asp:TextBox>  
                            </EditItemTemplate>  
                            <ItemTemplate>  
                                <asp:Label ID="lbldesignation" runat="server" Text='<%# Bind("Designation") %>'></asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField> 

                          <asp:TemplateField HeaderText="role">  
                            <EditItemTemplate>  
                                <asp:TextBox ID="txtrole" runat="server" Text='<%# Bind("Role") %>'></asp:TextBox>  
                            </EditItemTemplate>  
                            <ItemTemplate>  
                                <asp:Label ID="lblrole" runat="server" Text='<%# Bind("Role") %>'></asp:Label>  
                            </ItemTemplate>  
                        </asp:TemplateField> 

                          </Columns> 
                </asp:GridView> 
         </td>
     </tr>
 </table>   
    </div>
 


     </asp:Content>
 
